module.exports = {
  charging: 'Charging Turnip',
  nick: 'Technologic Nick',
  rockstar: 'rockstar modder',
  turbo: 'Turbo Biscuit',
  futureMapper: 'FutureMapper',
  tomatech: '🍅Tomatech',
  modGamer: 'ModGamer29',
  questionMark: 'Question Mark',
  ivan: 'IvanCoHe',
  bananaCat: 'BananaCat',
  dartFrog: 'Dart Frog',
  redBoi: 'Red Boi',
  vajdani: 'Vajdani',
  nothingMod: 'Nothing Mod (aka Komendowy Muzykant)',
};
